version: '3'

# Builds Dev environment, with hotloading.
# Usage: docker-compose -f docker-dev.yml up -d

# UI -> localhost:8000
# Backend -> localhost:5000
# db -> localhost:5800 

services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5800
    command: -p 5800
    ports:
      - '5800:5800'
    volumes: 
      - ./db:/var/lib/postgresql/data
volumes:
  db:
    driver: local