version: '3'
services:
  app:
    build: ./app
    volumes: 
      - ./app:/user/src/app
    working_dir: /user/src/
    command: python -m flask run --host=0.0.0.0 
    env_file:
      - ./.env
    environment:
      - FLASK_APP=app.main
      - APP_CONFIG_FILE=/user/src/config.py
      # - APP_SETTINGS="config.DevelopmentConfig"
      # - DATABASE_URL="postgresql://postgres:postgres@host.docker.internal:5432/postgres"
      # - DATABASE_HOST="localhost"
      # - DATABASE_NAME="postgres"
      # - DATABASE_USER="postgres"
      # - DATABASE_PASSWORD="postgres"
      # - PROD_API_URL="http://uwbadminton.live/api/"
      # - DomainName="http://127.0.0.1:5000/api"
    ports:
      - '5000:5000'


  web:
    build: ./front-end
    volumes: 
      - ./front-end:/user/src/app
    working_dir: /user/src/app
    command: npm run dev2
    environment:
      - FLASK_APP=app.main
      - APP_CONFIG_FILE=/user/src/config.py
      - REACT_APP_DOMAIN_NAME=http://127.0.0.1:5000/api
    ports:
      - '8000:3000'

    
    
